swh/deposit/migrations/0021: Fix migration script
Prior to this commit, running this script would not work when actually
triggered on a db with data:

```
swhdeposit@deposit:~$ django-admin migrate --settings=swh.deposit.settings.production
Operations to perform:
  Apply all migrations: auth, contenttypes, deposit, sessions
Running migrations:
  Applying deposit.0021_deposit_origin_url_20201124_1438...Traceback (most recent call last):
...
TypeError: guess_deposit_origin_url() missing 1 required positional argument: 'deposit'
```